title: Travel the world
author: Queen
email: queeninnpalace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  If you like travelling then this is the place you should be looking for.
  Make your Journey a memorable one

# social links
twitter_username: Hope # DO NOT include the @ character, or else the build will fail!
github_username:  Rani-14 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
